#!/usr/bin/env python3
"""Add the "from the community" post to the website news, nine languages.

    aggiungi-novita-community.py <repo>

Inserts one entry at the top of `news` in website/src/news.ts. Idempotent.
"""
import os
import sys

p = os.path.join(sys.argv[1], "website", "src", "news.ts")
t = open(p, encoding="utf-8").read()
if "community-2026-09" in t:
    print("gia' presente")
    sys.exit(0)
voce = r'''  {
    // community-2026-09
    data: '2026-09-11',
    quando: { it: "11 settembre 2026", en: "11 September 2026", pl: "11 września 2026", uk: "11 вересня 2026", ru: "11 сентября 2026", es: "11 de septiembre de 2026", pt: "11 de setembro de 2026", de: "11. September 2026", fr: "11 septembre 2026" },
    etichetta: { it: "community", en: "community", pl: "społeczność", uk: "спільнота", ru: "сообщество", es: "comunidad", pt: "comunidade", de: "Community", fr: "communauté" },
    titolo: {
      it: "Quello che abbiamo preso dalla community BC-250, e quello che no",
      en: "What we took from the BC-250 community, and what we did not",
      pl: "Co wzięliśmy od społeczności BC-250, a czego nie",
      uk: "Що ми взяли від спільноти BC-250, а що ні",
      ru: "Что мы взяли у сообщества BC-250, а что нет",
      es: "Lo que hemos tomado de la comunidad BC-250, y lo que no",
      pt: "O que tirámos da comunidade BC-250, e o que não",
      de: "Was wir von der BC-250-Community übernommen haben, und was nicht",
      fr: "Ce que nous avons pris à la communauté BC-250, et ce que nous n'avons pas pris"
    },
    testo: {
      it: "Abbiamo passato in rassegna tutto quello che la community della BC-250 ha pubblicato negli ultimi mesi e provato ogni pezzo sulla nostra scheda. Entrano nella distribuzione: il Control Center si guida anche <strong>col controller</strong> (croce, A, B, LB/RB per le sezioni) ed esporta le registrazioni del Monitor in CSV; la tabella ACPI con i metodi mancanti (e-tho); l'heap di memoria unificato per RADV, la cache degli shader a 10 GB e il quantum audio a 512; lo <strong>sblocco degli 8 core prima di GRUB</strong>, un programma EFI di Hexxeh che evita il riavvio dentro l'installatore; e due patch del kernel, per il DualSense dietro un bridge e per lo YCbCr 4:4:4 con deep color sui dongle DisplayPort-HDMI. Provati e lasciati in laboratorio, perché i loro repository non hanno una licenza: i mesh shader nativi (che per ora piantano la GPU al primo disegno) e il Dolby Digital 5.1 in tempo reale. Il registro completo, con fonti e risultati, è in <code>docs/COMMUNITY.md</code>.",
      en: "We went through everything the BC-250 community published in the last months and tried every piece on our board. Into the distribution: the Control Center can be driven <strong>with a controller</strong> (D-pad, A, B, LB/RB for the sections) and exports Monitor recordings as CSV; the ACPI table with the missing methods (e-tho); the unified memory heap for RADV, a 10 GB shader cache and a 512 audio quantum; the <strong>8-core unlock before GRUB</strong>, an EFI program by Hexxeh that avoids the reboot inside the installer; and two kernel patches, for a DualSense behind a bridge and for YCbCr 4:4:4 with deep color on DisplayPort-to-HDMI dongles. Tried and left in the lab, because their repositories carry no license: native mesh shaders (which for now hang the GPU on the first draw) and real-time Dolby Digital 5.1. The full ledger, with sources and results, is in <code>docs/COMMUNITY.md</code>.",
      pl: "Przejrzeliśmy wszystko, co społeczność BC-250 opublikowała w ostatnich miesiącach, i wypróbowaliśmy każdy element na naszej płycie. Do dystrybucji wchodzą: Control Center da się obsługiwać <strong>kontrolerem</strong> (krzyżak, A, B, LB/RB dla sekcji) i eksportuje nagrania Monitora do CSV; tabela ACPI z brakującymi metodami (e-tho); ujednolicona sterta pamięci dla RADV, pamięć podręczna shaderów 10 GB i kwant audio 512; <strong>odblokowanie 8 rdzeni przed GRUB-em</strong>, program EFI od Hexxeha, który unika restartu w instalatorze; oraz dwie łatki jądra, dla DualSense za mostkiem i dla YCbCr 4:4:4 z deep color na przejściówkach DisplayPort-HDMI. Wypróbowane i zostawione w laboratorium, bo ich repozytoria nie mają licencji: natywne mesh shadery (które na razie zawieszają GPU przy pierwszym rysowaniu) i Dolby Digital 5.1 w czasie rzeczywistym. Pełny rejestr, ze źródłami i wynikami, jest w <code>docs/COMMUNITY.md</code>.",
      uk: "Ми переглянули все, що спільнота BC-250 опублікувала за останні місяці, і випробували кожну річ на нашій платі. У дистрибутив входять: Control Center можна керувати <strong>контролером</strong> (хрестовина, A, B, LB/RB для розділів) і він експортує записи Монітора у CSV; таблиця ACPI з відсутніми методами (e-tho); об'єднана купа пам'яті для RADV, кеш шейдерів на 10 ГБ і аудіоквант 512; <strong>розблокування 8 ядер до GRUB</strong>, програма EFI від Hexxeh, яка уникає перезавантаження всередині інсталятора; і два патчі ядра, для DualSense за містком і для YCbCr 4:4:4 із deep color на перехідниках DisplayPort-HDMI. Випробувані й залишені в лабораторії, бо їхні репозиторії не мають ліцензії: нативні mesh-шейдери (які поки що вішають GPU на першому малюванні) та Dolby Digital 5.1 у реальному часі. Повний реєстр із джерелами та результатами в <code>docs/COMMUNITY.md</code>.",
      ru: "Мы просмотрели всё, что сообщество BC-250 опубликовало за последние месяцы, и проверили каждую вещь на нашей плате. В дистрибутив входят: Control Center можно управлять <strong>контроллером</strong> (крестовина, A, B, LB/RB для разделов), и он экспортирует записи Монитора в CSV; таблица ACPI с недостающими методами (e-tho); объединённая куча памяти для RADV, кэш шейдеров на 10 ГБ и аудиоквант 512; <strong>разблокировка 8 ядер до GRUB</strong>, EFI-программа от Hexxeh, которая избавляет от перезагрузки внутри установщика; и два патча ядра, для DualSense за мостом и для YCbCr 4:4:4 с deep color на переходниках DisplayPort-HDMI. Проверены и оставлены в лаборатории, потому что у их репозиториев нет лицензии: нативные mesh-шейдеры (которые пока вешают GPU на первой отрисовке) и Dolby Digital 5.1 в реальном времени. Полный реестр с источниками и результатами в <code>docs/COMMUNITY.md</code>.",
      es: "Hemos repasado todo lo que la comunidad de la BC-250 ha publicado en los últimos meses y probado cada pieza en nuestra placa. Entran en la distribución: el Control Center se maneja también <strong>con el mando</strong> (cruceta, A, B, LB/RB para las secciones) y exporta las grabaciones del Monitor en CSV; la tabla ACPI con los métodos que faltaban (e-tho); el heap de memoria unificado para RADV, la caché de shaders de 10 GB y el quantum de audio a 512; el <strong>desbloqueo de los 8 núcleos antes de GRUB</strong>, un programa EFI de Hexxeh que evita el reinicio dentro del instalador; y dos parches del kernel, para el DualSense tras un puente y para YCbCr 4:4:4 con deep color en los adaptadores DisplayPort-HDMI. Probados y dejados en el laboratorio, porque sus repositorios no tienen licencia: los mesh shaders nativos (que por ahora cuelgan la GPU al primer dibujo) y el Dolby Digital 5.1 en tiempo real. El registro completo, con fuentes y resultados, está en <code>docs/COMMUNITY.md</code>.",
      pt: "Passámos em revista tudo o que a comunidade da BC-250 publicou nos últimos meses e provámos cada peça na nossa placa. Entram na distribuição: o Control Center conduz-se também <strong>com o comando</strong> (cruz, A, B, LB/RB para as secções) e exporta as gravações do Monitor em CSV; a tabela ACPI com os métodos em falta (e-tho); o heap de memória unificado para RADV, a cache de shaders de 10 GB e o quantum de áudio a 512; o <strong>desbloqueio dos 8 núcleos antes do GRUB</strong>, um programa EFI do Hexxeh que evita o reinício dentro do instalador; e dois patches do kernel, para o DualSense atrás de uma ponte e para YCbCr 4:4:4 com deep color nos adaptadores DisplayPort-HDMI. Provados e deixados no laboratório, porque os repositórios deles não têm licença: os mesh shaders nativos (que por agora bloqueiam a GPU ao primeiro desenho) e o Dolby Digital 5.1 em tempo real. O registo completo, com fontes e resultados, está em <code>docs/COMMUNITY.md</code>.",
      de: "Wir haben alles durchgesehen, was die BC-250-Community in den letzten Monaten veröffentlicht hat, und jedes Stück auf unserer Karte ausprobiert. In die Distribution kommen: das Control Center lässt sich auch <strong>mit dem Controller</strong> bedienen (Steuerkreuz, A, B, LB/RB für die Bereiche) und exportiert die Monitor-Aufzeichnungen als CSV; die ACPI-Tabelle mit den fehlenden Methoden (e-tho); der vereinheitlichte Speicher-Heap für RADV, ein 10-GB-Shader-Cache und ein Audio-Quantum von 512; die <strong>Freischaltung der 8 Kerne vor GRUB</strong>, ein EFI-Programm von Hexxeh, das den Neustart im Installer überflüssig macht; und zwei Kernel-Patches, für einen DualSense hinter einer Bridge und für YCbCr 4:4:4 mit Deep Color auf DisplayPort-HDMI-Adaptern. Ausprobiert und im Labor gelassen, weil ihre Repositories keine Lizenz haben: native Mesh-Shader (die vorerst die GPU beim ersten Zeichnen aufhängen) und Dolby Digital 5.1 in Echtzeit. Das vollständige Verzeichnis mit Quellen und Ergebnissen steht in <code>docs/COMMUNITY.md</code>.",
      fr: "Nous avons passé en revue tout ce que la communauté BC-250 a publié ces derniers mois et essayé chaque pièce sur notre carte. Entrent dans la distribution : le Control Center se pilote aussi <strong>à la manette</strong> (croix, A, B, LB/RB pour les sections) et exporte les enregistrements du Moniteur en CSV ; la table ACPI avec les méthodes manquantes (e-tho) ; le tas de mémoire unifié pour RADV, un cache de shaders de 10 Go et un quantum audio de 512 ; le <strong>déblocage des 8 cœurs avant GRUB</strong>, un programme EFI de Hexxeh qui évite le redémarrage dans l'installateur ; et deux correctifs du noyau, pour une DualSense derrière un pont et pour le YCbCr 4:4:4 avec deep color sur les adaptateurs DisplayPort-HDMI. Essayés et laissés au laboratoire, parce que leurs dépôts n'ont pas de licence : les mesh shaders natifs (qui pour l'instant bloquent le GPU au premier tracé) et le Dolby Digital 5.1 en temps réel. Le registre complet, avec sources et résultats, est dans <code>docs/COMMUNITY.md</code>."
    },
  },
'''
a = "export const news: Post[] = [\n"
assert a in t
t = t.replace(a, a + voce, 1)
open(p, "w", encoding="utf-8").write(t)
print("novita' aggiunta")
