#!/usr/bin/env python3
"""The evening strings of 2026-09-11 (Tuner and Monitor rework) in the seven
dictionaries, then the merge into the shared ones.

    aggiungi-traduzioni-1109b.py <repo>
"""
import json
import os
import subprocess
import sys

repo = sys.argv[1]
d = os.path.join(repo, "apps", "control-center", "i18n")
L = ("de", "es", "fr", "pl", "pt", "ru", "uk")


def T(*tr):
    return dict(zip(L, tr))


NUOVE = {
    "%d MHz @ %d: %s (min %d MHz)": T("%d MHz @ %d: %s (min %d MHz)", "%d MHz @ %d: %s (mín %d MHz)", "%d MHz @ %d : %s (min %d MHz)", "%d MHz @ %d: %s (min %d MHz)", "%d MHz @ %d: %s (mín %d MHz)", "%d МГц @ %d: %s (мин %d МГц)", "%d МГц @ %d: %s (мін %d МГц)"),
    "(empty)": T("(leer)", "(vacío)", "(vide)", "(pusty)", "(vazio)", "(пусто)", "(порожньо)"),
    "24 CU: %s GFLOPS": T("24 CU: %s GFLOPS", "24 CU: %s GFLOPS", "24 CU : %s GFLOPS", "24 CU: %s GFLOPS", "24 CU: %s GFLOPS", "24 CU: %s GFLOPS", "24 CU: %s GFLOPS"),
    "Above it the thermal guard slows by 100 MHz at a time, then raises again.": T("Darüber drosselt der Temperaturwächter um jeweils 100 MHz und hebt danach wieder an.", "Por encima, la guardia térmica frena de 100 MHz en 100 MHz y luego vuelve a subir.", "Au-dessus, la garde thermique ralentit de 100 MHz à la fois, puis remonte.", "Powyżej strażnik termiczny zwalnia po 100 MHz, a potem znów podnosi.", "Acima, a guarda térmica abranda 100 MHz de cada vez e depois volta a subir.", "Выше этого тепловая защита снижает по 100 МГц за раз, затем снова поднимает.", "Вище цього теплова охорона знижує по 100 МГц за раз, потім знову піднімає."),
    "Active CUs": T("Aktive CUs", "CU activas", "CU actives", "Aktywne CU", "CU ativas", "Активные CU", "Активні CU"),
    "BC-250 · znver2": T("BC-250 · znver2", "BC-250 · znver2", "BC-250 · znver2", "BC-250 · znver2", "BC-250 · znver2", "BC-250 · znver2", "BC-250 · znver2"),
    "Balanced 2000": T("Ausgewogen 2000", "Equilibrado 2000", "Équilibré 2000", "Zbalansowany 2000", "Equilibrado 2000", "Сбалансированный 2000", "Збалансований 2000"),
    "Before boot (EFI)": T("Vor dem Start (EFI)", "Antes del arranque (EFI)", "Avant le démarrage (EFI)", "Przed startem (EFI)", "Antes do arranque (EFI)", "До загрузки (EFI)", "До завантаження (EFI)"),
    "Cannot read %s: %s": T("%s kann nicht gelesen werden: %s", "No puedo leer %s: %s", "Impossible de lire %s : %s", "Nie mogę odczytać %s: %s", "Não consigo ler %s: %s", "Не удаётся прочитать %s: %s", "Не вдається прочитати %s: %s"),
    "Cautious 1850": T("Vorsichtig 1850", "Prudente 1850", "Prudent 1850", "Ostrożny 1850", "Prudente 1850", "Осторожный 1850", "Обережний 1850"),
    "Close recording": T("Aufzeichnung schließen", "Cerrar grabación", "Fermer l'enregistrement", "Zamknij nagranie", "Fechar gravação", "Закрыть запись", "Закрити запис"),
    "Curve knots": T("Kurvenpunkte", "Puntos de la curva", "Points de la courbe", "Punkty krzywej", "Pontos da curva", "Узлы кривой", "Вузли кривої"),
    "Documentation": T("Dokumentation", "Documentación", "Documentation", "Dokumentacja", "Documentação", "Документация", "Документація"),
    "Does not hold: previous values are back.": T("Hält nicht: die vorherigen Werte sind zurück.", "No aguanta: han vuelto los valores anteriores.", "Ne tient pas : les valeurs précédentes sont revenues.", "Nie trzyma: poprzednie wartości wróciły.", "Não aguenta: os valores anteriores voltaram.", "Не держит: прежние значения возвращены.", "Не тримає: попередні значення повернуто."),
    "EFI unlock %s.": T("EFI-Freischaltung %s.", "Desbloqueo EFI %s.", "Déblocage EFI %s.", "Odblokowanie EFI %s.", "Desbloqueio EFI %s.", "Разблокировка EFI %s.", "Розблокування EFI %s."),
    "Empty recording.": T("Leere Aufzeichnung.", "Grabación vacía.", "Enregistrement vide.", "Puste nagranie.", "Gravação vazia.", "Пустая запись.", "Порожній запис."),
    "Engine": T("Engine", "Motor", "Moteur", "Silnik", "Motor", "Движок", "Рушій"),
    "Every row is a knot: type MHz and mV. + adds a knot after the selected one, − removes it.": T("Jede Zeile ist ein Punkt: MHz und mV eintippen. + fügt nach dem gewählten einen Punkt hinzu, − entfernt ihn.", "Cada fila es un punto: escribe MHz y mV. + añade un punto después del elegido, − lo quita.", "Chaque ligne est un point : tapez MHz et mV. + ajoute un point après celui choisi, − le retire.", "Każdy wiersz to punkt: wpisz MHz i mV. + dodaje punkt za wybranym, − go usuwa.", "Cada linha é um ponto: escreva MHz e mV. + acrescenta um ponto a seguir ao escolhido, − retira-o.", "Каждая строка — узел: введите МГц и мВ. + добавляет узел после выбранного, − удаляет его.", "Кожен рядок — вузол: введіть МГц і мВ. + додає вузол після вибраного, − вилучає його."),
    "From 3600 to 4000 MHz with growing undervolt, thirty seconds a step, stops at the first that does not hold. The last step can hang some boards: the watchdog reboots and the good values are back. Proceed?": T("Von 3600 bis 4000 MHz mit wachsendem Undervolt, dreißig Sekunden pro Stufe, hält bei der ersten, die nicht hält. Die letzte Stufe kann manche Karten aufhängen: der Watchdog startet neu und die guten Werte sind zurück. Fortfahren?", "De 3600 a 4000 MHz con undervolt creciente, treinta segundos por escalón, se para en el primero que no aguanta. El último escalón puede colgar algunas placas: el watchdog reinicia y vuelven los valores buenos. ¿Continuar?", "De 3600 à 4000 MHz avec un undervolt croissant, trente secondes par palier, s'arrête au premier qui ne tient pas. Le dernier palier peut bloquer certaines cartes : le watchdog redémarre et les bonnes valeurs reviennent. Continuer ?", "Od 3600 do 4000 MHz z rosnącym undervoltem, trzydzieści sekund na stopień, zatrzymuje się na pierwszym, który nie trzyma. Ostatni stopień może zawiesić niektóre płyty: watchdog restartuje i dobre wartości wracają. Kontynuować?", "De 3600 a 4000 MHz com undervolt crescente, trinta segundos por degrau, pára no primeiro que não aguenta. O último degrau pode bloquear algumas placas: o watchdog reinicia e os valores bons voltam. Continuar?", "От 3600 до 4000 МГц с растущим андервольтом, тридцать секунд на шаг, остановка на первом, который не держит. Последний шаг может повесить некоторые платы: watchdog перезагружает и хорошие значения возвращаются. Продолжить?", "Від 3600 до 4000 МГц зі зростаючим андервольтом, тридцять секунд на крок, зупинка на першому, який не тримає. Останній крок може повісити деякі плати: watchdog перезавантажує і добрі значення повертаються. Продовжити?"),
    "Green on, red off, grey always on (the driver keeps it). Every cell is a pair of CUs.": T("Grün an, rot aus, grau immer an (der Treiber hält es). Jede Zelle ist ein CU-Paar.", "Verde encendida, roja apagada, gris siempre encendida (la mantiene el driver). Cada celda es un par de CU.", "Vert allumé, rouge éteint, gris toujours allumé (le pilote le garde). Chaque case est une paire de CU.", "Zielone włączone, czerwone wyłączone, szare zawsze włączone (trzyma je sterownik). Każda komórka to para CU.", "Verde ligada, vermelha desligada, cinzenta sempre ligada (o driver mantém-na). Cada célula é um par de CU.", "Зелёный включён, красный выключен, серый всегда включён (его держит драйвер). Каждая ячейка — пара CU.", "Зелений увімкнено, червоний вимкнено, сірий завжди увімкнено (його тримає драйвер). Кожна комірка — пара CU."),
    "HUD": T("HUD", "HUD", "HUD", "HUD", "HUD", "HUD", "HUD"),
    "Hexxeh's EFI program, first in the boot order: unlocks and warm-resets before the system. Verified: one boot only.": T("Hexxehs EFI-Programm, als erstes in der Startreihenfolge: schaltet frei und macht einen warmen Reset vor dem System. Geprüft: nur ein Start.", "El programa EFI de Hexxeh, primero en el orden de arranque: desbloquea y hace un reinicio en caliente antes del sistema. Verificado: un solo arranque.", "Le programme EFI de Hexxeh, premier dans l'ordre de démarrage : débloque et fait un reset à chaud avant le système. Vérifié : un seul démarrage.", "Program EFI Hexxeha, pierwszy w kolejności startu: odblokowuje i robi ciepły reset przed systemem. Sprawdzone: tylko jeden start.", "O programa EFI do Hexxeh, primeiro na ordem de arranque: desbloqueia e faz um reset a quente antes do sistema. Verificado: um só arranque.", "EFI-программа Hexxeh, первая в порядке загрузки: разблокирует и делает тёплый сброс до системы. Проверено: всего одна загрузка.", "EFI-програма Hexxeh, перша в порядку завантаження: розблоковує і робить теплий скид до системи. Перевірено: лише одне завантаження."),
    "Highest that holds: %d MHz @ %d. Press Apply.": T("Höchstes, das hält: %d MHz @ %d. Anwenden drücken.", "Máximo que aguanta: %d MHz @ %d. Pulsa Aplicar.", "Le plus haut qui tient : %d MHz @ %d. Appuyez sur Appliquer.", "Najwyższe, które trzyma: %d MHz @ %d. Naciśnij Zastosuj.", "O mais alto que aguenta: %d MHz @ %d. Carregue em Aplicar.", "Максимум, который держит: %d МГц @ %d. Нажмите Применить.", "Найвище, що тримає: %d МГц @ %d. Натисніть Застосувати."),
    "Holds. Press Apply to keep it.": T("Hält. Anwenden drücken, um es zu behalten.", "Aguanta. Pulsa Aplicar para mantenerlo.", "Tient. Appuyez sur Appliquer pour le garder.", "Trzyma. Naciśnij Zastosuj, żeby zachować.", "Aguenta. Carregue em Aplicar para manter.", "Держит. Нажмите Применить, чтобы сохранить.", "Тримає. Натисніть Застосувати, щоб зберегти."),
    "How far the governor may push the clock. 2100 holds on the development board; go up 50 at a time and try Cyberpunk.": T("Wie weit der Governor den Takt treiben darf. 2100 hält auf der Entwicklungskarte; in 50er-Schritten hochgehen und Cyberpunk probieren.", "Hasta dónde puede empujar el reloj el governor. 2100 aguanta en la placa de desarrollo; sube de 50 en 50 y prueba Cyberpunk.", "Jusqu'où le governor peut pousser l'horloge. 2100 tient sur la carte de développement ; montez de 50 en 50 et essayez Cyberpunk.", "Jak wysoko governor może pchnąć zegar. 2100 trzyma na płycie deweloperskiej; podnoś po 50 i sprawdź Cyberpunk.", "Até onde o governor pode empurrar o relógio. 2100 aguenta na placa de desenvolvimento; suba 50 de cada vez e experimente o Cyberpunk.", "Насколько governor может поднимать частоту. 2100 держит на плате разработки; поднимайте по 50 и проверяйте Cyberpunk.", "Наскільки governor може підняти частоту. 2100 тримає на платі розробки; піднімайте по 50 і перевіряйте Cyberpunk."),
    "Hub": T("Hub", "Hub", "Hub", "Hub", "Hub", "Hub", "Hub"),
    "Knots": T("Punkte", "Puntos", "Points", "Punkty", "Pontos", "Узлы", "Вузли"),
    "Looking for the maximum…": T("Suche das Maximum…", "Buscando el máximo…", "Recherche du maximum…", "Szukam maksimum…", "À procura do máximo…", "Ищу максимум…", "Шукаю максимум…"),
    "Looking for the undervolt at %d MHz: twelve seconds a step, stopping at the first that does not hold.": T("Suche den Undervolt bei %d MHz: zwölf Sekunden pro Stufe, Stopp bei der ersten, die nicht hält.", "Buscando el undervolt a %d MHz: doce segundos por escalón, parando en el primero que no aguanta.", "Recherche de l'undervolt à %d MHz : douze secondes par palier, arrêt au premier qui ne tient pas.", "Szukam undervoltu dla %d MHz: dwanaście sekund na stopień, stop na pierwszym, który nie trzyma.", "À procura do undervolt a %d MHz: doze segundos por degrau, parando no primeiro que não aguenta.", "Ищу андервольт для %d МГц: двенадцать секунд на шаг, остановка на первом, который не держит.", "Шукаю андервольт для %d МГц: дванадцять секунд на крок, зупинка на першому, який не тримає."),
    "Low-load ticks before stepping down.": T("Takte mit niedriger Last, bevor eine Stufe runtergeht.", "Ciclos de carga baja antes de bajar un escalón.", "Cycles de faible charge avant de descendre d'un palier.", "Cykle niskiego obciążenia przed zejściem o stopień.", "Ciclos de carga baixa antes de descer um degrau.", "Тактов низкой нагрузки перед шагом вниз.", "Тактів низького навантаження перед кроком униз."),
    "Measured 2100": T("Gemessen 2100", "Medido 2100", "Mesuré 2100", "Zmierzony 2100", "Medido 2100", "Измеренный 2100", "Виміряний 2100"),
    "Memory set aside for the GPU in the CMOS, in force from the next boot. With the 512 MB dynamic split some games pick low textures: if blurry, try 4 or 6 GB fixed.": T("Im CMOS für die GPU reservierter Speicher, gültig ab dem nächsten Start. Mit der dynamischen 512-MB-Aufteilung wählen manche Spiele niedrige Texturen: wenn unscharf, 4 oder 6 GB fest probieren.", "Memoria reservada a la GPU en la CMOS, vale desde el próximo arranque. Con el reparto dinámico de 512 MB algunos juegos eligen texturas bajas: si se ven borrosas, prueba 4 o 6 GB fijos.", "Mémoire réservée au GPU dans la CMOS, en vigueur au prochain démarrage. Avec le partage dynamique de 512 Mo certains jeux choisissent des textures basses : si c'est flou, essayez 4 ou 6 Go fixes.", "Pamięć zarezerwowana dla GPU w CMOS, obowiązuje od następnego startu. Przy dynamicznym podziale 512 MB niektóre gry wybierają niskie tekstury: jeśli są rozmyte, spróbuj 4 lub 6 GB na stałe.", "Memória reservada para a GPU no CMOS, em vigor a partir do próximo arranque. Com a divisão dinâmica de 512 MB alguns jogos escolhem texturas baixas: se estiverem desfocadas, tente 4 ou 6 GB fixos.", "Память, выделенная GPU в CMOS, действует со следующей загрузки. При динамическом разделе 512 МБ некоторые игры выбирают низкие текстуры: если размыто, попробуйте 4 или 6 ГБ фиксированно.", "Пам'ять, виділена для GPU в CMOS, діє з наступного завантаження. З динамічним розподілом 512 МБ деякі ігри обирають низькі текстури: якщо розмито, спробуйте 4 або 6 ГБ фіксовано."),
    "Millivolts added only while climbing. Shipped: 10.": T("Millivolt, die nur beim Hochgehen dazukommen. Ausgeliefert: 10.", "Milivoltios añadidos solo al subir. De serie: 10.", "Millivolts ajoutés seulement en montée. Livré : 10.", "Miliwolty dodawane tylko przy wchodzeniu w górę. Domyślnie: 10.", "Milivolts acrescentados só a subir. De série: 10.", "Милливольты, добавляемые только при подъёме. По умолчанию: 10.", "Мілівольти, що додаються лише під час підйому. Типово: 10."),
    "Not even step 0 holds at this clock.": T("Nicht einmal Stufe 0 hält bei diesem Takt.", "Ni siquiera el escalón 0 aguanta a esta frecuencia.", "Même le palier 0 ne tient pas à cette fréquence.", "Nawet stopień 0 nie trzyma przy tym zegarze.", "Nem o degrau 0 aguenta a esta frequência.", "Даже шаг 0 не держит на этой частоте.", "Навіть крок 0 не тримає на цій частоті."),
    "One chart per quantity, real numbers on the axes. Click a legend entry to hide it. REC records, Open reopens, CSV exports.": T("Ein Diagramm pro Größe, echte Zahlen auf den Achsen. Klick auf einen Legendeneintrag blendet ihn aus. REC zeichnet auf, Öffnen lädt, CSV exportiert.", "Un gráfico por magnitud, números reales en los ejes. Clic en una entrada de la leyenda para ocultarla. REC graba, Abrir reabre, CSV exporta.", "Un graphique par grandeur, de vrais nombres sur les axes. Cliquez sur une entrée de la légende pour la masquer. REC enregistre, Ouvrir rouvre, CSV exporte.", "Jeden wykres na wielkość, prawdziwe liczby na osiach. Kliknij wpis legendy, żeby go ukryć. REC nagrywa, Otwórz otwiera, CSV eksportuje.", "Um gráfico por grandeza, números reais nos eixos. Clique numa entrada da legenda para a esconder. REC grava, Abrir reabre, CSV exporta.", "Один график на величину, настоящие числа на осях. Щёлкните пункт легенды, чтобы скрыть его. REC записывает, Открыть открывает, CSV экспортирует.", "Один графік на величину, справжні числа на осях. Клацніть пункт легенди, щоб сховати його. REC записує, Відкрити відкриває, CSV експортує."),
    "Our governor forces the clock and takes on the protection: the ceiling drops when the board gets hot or draws too much.": T("Unser Governor erzwingt den Takt und übernimmt den Schutz: die Obergrenze sinkt, wenn die Karte heiß wird oder zu viel zieht.", "Nuestro governor fuerza el reloj y asume la protección: el techo baja cuando la placa se calienta o consume demasiado.", "Notre governor force l'horloge et prend en charge la protection : le plafond baisse quand la carte chauffe ou tire trop.", "Nasz governor wymusza zegar i bierze na siebie ochronę: sufit spada, gdy płyta się grzeje albo pobiera za dużo.", "O nosso governor força o relógio e assume a proteção: o teto desce quando a placa aquece ou puxa demasiado.", "Наш governor принудительно задаёт частоту и берёт на себя защиту: потолок снижается, когда плата греется или тянет слишком много.", "Наш governor примусово задає частоту і бере на себе захист: стеля знижується, коли плата гріється або тягне забагато."),
    "Our own power limit.": T("Unsere eigene Leistungsgrenze.", "Nuestro propio límite de potencia.", "Notre propre limite de puissance.", "Nasz własny limit mocy.", "O nosso próprio limite de potência.", "Наш собственный лимит мощности.", "Наш власний ліміт потужності."),
    "Panels:": T("Bereiche:", "Paneles:", "Panneaux :", "Panele:", "Painéis:", "Панели:", "Панелі:"),
    "Per-thread clock  (MHz)": T("Takt pro Thread  (MHz)", "Frecuencia por hilo  (MHz)", "Fréquence par thread  (MHz)", "Zegar na wątek  (MHz)", "Frequência por thread  (MHz)", "Частота на поток  (МГц)", "Частота на потік  (МГц)"),
    "Raises the voltage when the sensor sees it sag below the curve. Off by default.": T("Hebt die Spannung an, wenn der Sensor sie unter die Kurve sacken sieht. Standardmäßig aus.", "Sube la tensión cuando el sensor la ve caer por debajo de la curva. Apagado de serie.", "Relève la tension quand le capteur la voit chuter sous la courbe. Désactivé par défaut.", "Podnosi napięcie, gdy czujnik widzi, że spada poniżej krzywej. Domyślnie wyłączone.", "Sobe a tensão quando o sensor a vê cair abaixo da curva. Desligado de série.", "Поднимает напряжение, когда датчик видит его просадку ниже кривой. По умолчанию выключено.", "Піднімає напругу, коли датчик бачить її просідання нижче кривої. Типово вимкнено."),
    "Remote Manager": T("Remote Manager", "Remote Manager", "Remote Manager", "Remote Manager", "Remote Manager", "Remote Manager", "Remote Manager"),
    "SMT %s": T("SMT %s", "SMT %s", "SMT %s", "SMT %s", "SMT %s", "SMT %s", "SMT %s"),
    "Scheduler": T("Scheduler", "Planificador", "Ordonnanceur", "Planista", "Escalonador", "Планировщик", "Планувальник"),
    "Status": T("Status", "Estado", "État", "Stan", "Estado", "Состояние", "Стан"),
    "Steps of 6.25 mV taken off the CPU: less heat, same clock, as far as it holds.": T("Stufen von 6,25 mV, die der CPU abgezogen werden: weniger Hitze, gleicher Takt, so weit es hält.", "Escalones de 6,25 mV quitados a la CPU: menos calor, misma frecuencia, hasta donde aguante.", "Paliers de 6,25 mV retirés au CPU : moins de chaleur, même fréquence, tant que ça tient.", "Stopnie po 6,25 mV odjęte CPU: mniej ciepła, ten sam zegar, dopóki trzyma.", "Degraus de 6,25 mV tirados à CPU: menos calor, mesma frequência, até onde aguentar.", "Шаги по 6,25 мВ, снятые с CPU: меньше тепла, та же частота, пока держит.", "Кроки по 6,25 мВ, зняті з CPU: менше тепла, та сама частота, поки тримає."),
    "Stopped. Previous values are back.": T("Gestoppt. Die vorherigen Werte sind zurück.", "Parado. Han vuelto los valores anteriores.", "Arrêté. Les valeurs précédentes sont revenues.", "Zatrzymano. Poprzednie wartości wróciły.", "Parado. Os valores anteriores voltaram.", "Остановлено. Прежние значения возвращены.", "Зупинено. Попередні значення повернуто."),
    "Suggested: step %d (−%.0f mV). Press Apply.": T("Vorschlag: Stufe %d (−%.0f mV). Anwenden drücken.", "Sugerido: escalón %d (−%.0f mV). Pulsa Aplicar.", "Suggéré : palier %d (−%.0f mV). Appuyez sur Appliquer.", "Sugerowane: stopień %d (−%.0f mV). Naciśnij Zastosuj.", "Sugerido: degrau %d (−%.0f mV). Carregue em Aplicar.", "Предложено: шаг %d (−%.0f мВ). Нажмите Применить.", "Запропоновано: крок %d (−%.0f мВ). Натисніть Застосувати."),
    "Test: a minute of load on every thread…": T("Test: eine Minute Last auf jedem Thread…", "Test: un minuto de carga en todos los hilos…", "Test : une minute de charge sur chaque thread…", "Test: minuta obciążenia na każdym wątku…", "Teste: um minuto de carga em todos os threads…", "Тест: минута нагрузки на каждый поток…", "Тест: хвилина навантаження на кожен потік…"),
    "The clock under load. Above 3500 with eight cores heat is in charge.": T("Der Takt unter Last. Über 3500 mit acht Kernen hat die Hitze das Sagen.", "La frecuencia bajo carga. Por encima de 3500 con ocho núcleos manda el calor.", "La fréquence sous charge. Au-dessus de 3500 avec huit cœurs, c'est la chaleur qui commande.", "Zegar pod obciążeniem. Powyżej 3500 z ośmioma rdzeniami rządzi ciepło.", "A frequência sob carga. Acima de 3500 com oito núcleos manda o calor.", "Частота под нагрузкой. Выше 3500 с восемью ядрами командует тепло.", "Частота під навантаженням. Вище 3500 з вісьмома ядрами керує тепло."),
    "The fifteen-point curve measured on the development board: the one we ship.": T("Die auf der Entwicklungskarte gemessene Kurve mit fünfzehn Punkten: die, die wir ausliefern.", "La curva de quince puntos medida en la placa de desarrollo: la que enviamos.", "La courbe à quinze points mesurée sur la carte de développement : celle que nous livrons.", "Krzywa z piętnastu punktów zmierzona na płycie deweloperskiej: ta, którą wysyłamy.", "A curva de quinze pontos medida na placa de desenvolvimento: a que enviamos.", "Кривая из пятнадцати точек, измеренная на плате разработки: та, что мы поставляем.", "Крива з п'ятнадцяти точок, виміряна на платі розробки: та, яку ми постачаємо."),
    "The governor's voltage/frequency curve: drag a knot or type the number in the table. Apply runs it on trial for %d seconds with the old one kept on disk.": T("Die Spannungs-/Frequenzkurve des Governors: einen Punkt ziehen oder die Zahl in die Tabelle tippen. Anwenden lässt sie %d Sekunden auf Probe laufen, die alte bleibt auf der Platte.", "La curva tensión/frecuencia del governor: arrastra un punto o escribe el número en la tabla. Aplicar la prueba durante %d segundos con la vieja guardada en disco.", "La courbe tension/fréquence du governor : glissez un point ou tapez le nombre dans le tableau. Appliquer la met à l'essai %d secondes, l'ancienne restant sur le disque.", "Krzywa napięcie/częstotliwość governora: przeciągnij punkt albo wpisz liczbę w tabeli. Zastosuj uruchamia ją na próbę przez %d sekund, stara zostaje na dysku.", "A curva tensão/frequência do governor: arraste um ponto ou escreva o número na tabela. Aplicar põe-na à prova durante %d segundos com a antiga guardada no disco.", "Кривая напряжение/частота governor: перетащите узел или введите число в таблице. Применить запускает её на пробу на %d секунд, старая остаётся на диске.", "Крива напруга/частота governor: перетягніть вузол або введіть число в таблиці. Застосувати запускає її на пробу на %d секунд, стара лишається на диску."),
    "The sweet spot with the stock heatsink: nearly the same frames, ten degrees less.": T("Der beste Punkt mit dem Serienkühler: fast dieselben Bilder, zehn Grad weniger.", "El punto dulce con el disipador de serie: casi los mismos fotogramas, diez grados menos.", "Le point idéal avec le dissipateur d'origine : presque les mêmes images, dix degrés de moins.", "Optymalny punkt z fabrycznym radiatorem: prawie te same klatki, dziesięć stopni mniej.", "O ponto ideal com o dissipador de série: quase os mesmos fotogramas, dez graus a menos.", "Оптимум со штатным радиатором: почти те же кадры, на десять градусов меньше.", "Оптимум зі штатним радіатором: майже ті самі кадри, на десять градусів менше."),
    "The two cores the BC-250 keeps off: 6c/12t becomes 8c/16t, +20% measured. With the EFI unlock it happens before GRUB in a single boot; without it the service does it with one extra reboot on every cold start.": T("Die zwei Kerne, die die BC-250 abgeschaltet hält: aus 6c/12t wird 8c/16t, +20 % gemessen. Mit der EFI-Freischaltung passiert es vor GRUB in einem einzigen Start; ohne macht es der Dienst mit einem zusätzlichen Neustart bei jedem Kaltstart.", "Los dos núcleos que la BC-250 mantiene apagados: 6c/12t pasa a 8c/16t, +20 % medido. Con el desbloqueo EFI ocurre antes de GRUB en un solo arranque; sin él lo hace el servicio con un reinicio extra en cada arranque en frío.", "Les deux cœurs que la BC-250 garde éteints : 6c/12t devient 8c/16t, +20 % mesuré. Avec le déblocage EFI cela se fait avant GRUB en un seul démarrage ; sans, le service le fait avec un redémarrage de plus à chaque démarrage à froid.", "Dwa rdzenie, które BC-250 trzyma wyłączone: 6c/12t staje się 8c/16t, zmierzone +20 %. Z odblokowaniem EFI dzieje się to przed GRUB-em w jednym starcie; bez niego robi to usługa z dodatkowym restartem przy każdym zimnym starcie.", "Os dois núcleos que a BC-250 mantém desligados: 6c/12t passa a 8c/16t, +20 % medido. Com o desbloqueio EFI acontece antes do GRUB num só arranque; sem ele o serviço fá-lo com um reinício extra a cada arranque a frio.", "Два ядра, которые BC-250 держит выключенными: 6c/12t становится 8c/16t, измерено +20 %. С разблокировкой EFI это происходит до GRUB за одну загрузку; без неё это делает сервис с лишней перезагрузкой при каждом холодном старте.", "Два ядра, які BC-250 тримає вимкненими: 6c/12t стає 8c/16t, виміряно +20 %. З розблокуванням EFI це відбувається до GRUB за одне завантаження; без нього це робить сервіс із зайвим перезавантаженням при кожному холодному старті."),
    "Turns on one extra CU pair at a time under vkpeak and watches for GPU errors. Two or three minutes. Proceed?": T("Schaltet unter vkpeak jeweils ein zusätzliches CU-Paar ein und achtet auf GPU-Fehler. Zwei oder drei Minuten. Fortfahren?", "Enciende un par de CU extra a la vez bajo vkpeak y vigila errores de GPU. Dos o tres minutos. ¿Continuar?", "Allume une paire de CU supplémentaire à la fois sous vkpeak et surveille les erreurs GPU. Deux ou trois minutes. Continuer ?", "Włącza po jednej dodatkowej parze CU pod vkpeak i pilnuje błędów GPU. Dwie lub trzy minuty. Kontynuować?", "Liga um par de CU extra de cada vez sob o vkpeak e vigia erros da GPU. Dois ou três minutos. Continuar?", "Включает по одной дополнительной паре CU под vkpeak и следит за ошибками GPU. Две-три минуты. Продолжить?", "Вмикає по одній додатковій парі CU під vkpeak і стежить за помилками GPU. Дві-три хвилини. Продовжити?"),
    "Turns on one pair at a time under vkpeak and watches for GPU errors. Two or three minutes.": T("Schaltet unter vkpeak jeweils ein Paar ein und achtet auf GPU-Fehler. Zwei oder drei Minuten.", "Enciende un par a la vez bajo vkpeak y vigila errores de GPU. Dos o tres minutos.", "Allume une paire à la fois sous vkpeak et surveille les erreurs GPU. Deux ou trois minutes.", "Włącza po jednej parze pod vkpeak i pilnuje błędów GPU. Dwie lub trzy minuty.", "Liga um par de cada vez sob o vkpeak e vigia erros da GPU. Dois ou três minutos.", "Включает по одной паре под vkpeak и следит за ошибками GPU. Две-три минуты.", "Вмикає по одній парі під vkpeak і стежить за помилками GPU. Дві-три хвилини."),
    "Type how many CUs you want, in pairs: the cells light up by themselves, one column then the other. Or click the cells.": T("Tippe ein, wie viele CUs du willst, paarweise: die Zellen leuchten von selbst auf, erst eine Spalte, dann die andere. Oder klicke die Zellen.", "Escribe cuántas CU quieres, de dos en dos: las celdas se encienden solas, primero una columna y luego la otra. O pulsa las celdas.", "Tapez combien de CU vous voulez, par paires : les cases s'allument toutes seules, une colonne puis l'autre. Ou cliquez sur les cases.", "Wpisz, ile CU chcesz, parami: komórki zapalają się same, najpierw jedna kolumna, potem druga. Albo klikaj komórki.", "Escreva quantas CU quer, aos pares: as células acendem-se sozinhas, primeiro uma coluna e depois a outra. Ou clique nas células.", "Введите, сколько CU нужно, парами: ячейки зажигаются сами, сначала один столбец, потом другой. Или щёлкайте ячейки.", "Введіть, скільки CU потрібно, парами: комірки засвічуються самі, спочатку один стовпець, потім інший. Або клацайте комірки."),
    "Unlock the 8 cores": T("Die 8 Kerne freischalten", "Desbloquear los 8 núcleos", "Débloquer les 8 cœurs", "Odblokuj 8 rdzeni", "Desbloquear os 8 núcleos", "Разблокировать 8 ядер", "Розблокувати 8 ядер"),
    "does NOT hold": T("hält NICHT", "NO aguanta", "ne tient PAS", "NIE trzyma", "NÃO aguenta", "НЕ держит", "НЕ тримає"),
    "holds": T("hält", "aguanta", "tient", "trzyma", "aguenta", "держит", "тримає"),
    "installed, first at boot": T("installiert, als erstes beim Start", "instalado, primero al arrancar", "installé, premier au démarrage", "zainstalowane, pierwsze przy starcie", "instalado, primeiro no arranque", "установлено, первым при загрузке", "встановлено, першим при завантаженні"),
    "removed": T("entfernt", "quitado", "retiré", "usunięte", "removido", "удалено", "вилучено"),
    "samples": T("Messwerte", "muestras", "échantillons", "próbek", "amostras", "отсчётов", "відліків"),
    "testing…": T("Test läuft…", "probando…", "test en cours…", "testowanie…", "a testar…", "тестирую…", "тестую…"),
    "vkpeak measures the GPU GFLOPS with the curve in use. It does not prove a game stable.": T("vkpeak misst die GFLOPS der GPU mit der aktiven Kurve. Es beweist nicht, dass ein Spiel stabil ist.", "vkpeak mide los GFLOPS de la GPU con la curva en uso. No demuestra que un juego sea estable.", "vkpeak mesure les GFLOPS du GPU avec la courbe en cours. Il ne prouve pas qu'un jeu est stable.", "vkpeak mierzy GFLOPS GPU z używaną krzywą. Nie dowodzi stabilności gry.", "vkpeak mede os GFLOPS da GPU com a curva em uso. Não prova que um jogo é estável.", "vkpeak измеряет GFLOPS GPU с текущей кривой. Он не доказывает стабильность игры.", "vkpeak вимірює GFLOPS GPU з поточною кривою. Він не доводить стабільність гри."),
}

for lang in L:
    p = os.path.join(d, lang + ".json")
    with open(p, encoding="utf-8") as f:
        j = json.load(f)
    n = 0
    for en, tr in NUOVE.items():
        if en not in j:
            j[en] = tr[lang]
            n += 1
    with open(p, "w", encoding="utf-8") as f:
        json.dump(j, f, ensure_ascii=False, indent=1, sort_keys=True)
        f.write("\n")
    print(lang, "+%d" % n, "totale", len(j))

subprocess.run([sys.executable, os.path.join(repo, "apps", "control-center", "strumenti", "unisci-i18n.py"),
                os.path.join(repo, "apps", "control-center"),
                os.path.join(repo, "system", "usr", "share", "skillfish", "i18n")], check=True)
