#!/usr/bin/env python3
"""Add the Control Center post to the website news, in the nine languages.

    aggiungi-novita.py <repo>

Inserts one entry at the top of `news` in website/src/news.ts. Idempotent.
"""
import os
import sys

p = os.path.join(sys.argv[1], "website", "src", "news.ts")
t = open(p, encoding="utf-8").read()
if "control-center-2026-09" in t:
    print("gia' presente")
    sys.exit(0)
voce = r'''  {
    // control-center-2026-09
    data: '2026-09-11',
    quando: { it: "11 settembre 2026", en: "11 September 2026", pl: "11 września 2026", uk: "11 вересня 2026", ru: "11 сентября 2026", es: "11 de septiembre de 2026", pt: "11 de setembro de 2026", de: "11. September 2026", fr: "11 septembre 2026" },
    etichetta: { it: "novità", en: "new", pl: "nowość", uk: "новинка", ru: "новое", es: "novedad", pt: "novidade", de: "Neu", fr: "nouveauté" },
    titolo: {
      it: "Tutti gli strumenti in una finestra: il Control Center",
      en: "Every tool in one window: the Control Center",
      pl: "Wszystkie narzędzia w jednym oknie: Control Center",
      uk: "Усі інструменти в одному вікні: Control Center",
      ru: "Все инструменты в одном окне: Control Center",
      es: "Todas las herramientas en una ventana: el Control Center",
      pt: "Todas as ferramentas numa janela: o Control Center",
      de: "Alle Werkzeuge in einem Fenster: das Control Center",
      fr: "Tous les outils dans une fenêtre : le Control Center"
    },
    testo: {
      it: "Fino a ieri SkillFishOS aveva sette finestre: Tuner, Ventola, Monitor, Kernel, Snapshot, AI e il resto. Adesso ce n'è <strong>una sola</strong>, con dodici sezioni nella colonna a sinistra, e dentro ci sono anche cose che prima si facevano da terminale: la nostra Mesa da accendere per Steam, per Heroic o per tutto il sistema, lo schedulatore che parte con i giochi, l'installazione di GE-Proton 11, i profili. Il Tuner è stato riscritto attorno alla curva vera del governor: quindici punti che si trascinano, il tetto, e un Applica che <strong>mette la curva in prova</strong> con un conto alla rovescia mentre quella vecchia resta su disco. Se la scheda si pianta, riparte con la curva buona. Le stesse sezioni sono nel Remote Manager. Abbiamo rifatto i benchmark dopo il cambio: Cyberpunk 98 fps, Wukong 50, GravityMark 26.950, Superposition 12.560, cioè <strong>gli stessi numeri di prima</strong>, che è quello che deve fare una finestra. Arriva con <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      en: "Until yesterday SkillFishOS had seven windows: Tuner, Fan, Monitor, Kernel, Snapshots, AI and the rest. Now there is <strong>one</strong>, with twelve sections in the column on the left, and it holds things that used to need a terminal: our Mesa switched on for Steam, for Heroic or for the whole system, the scheduler that starts with a game, the GE-Proton 11 installer, the profiles. The Tuner was rewritten around the real curve of the governor: fifteen knots you drag, the ceiling, and an Apply that <strong>runs the curve on trial</strong> with a countdown while the old one stays on disk. If the board hangs, it comes back with the good curve. The same sections are in the Remote Manager. We ran the benchmarks again after the change: Cyberpunk 98 fps, Wukong 50, GravityMark 26,950, Superposition 12,560, that is <strong>the same numbers as before</strong>, which is what a window is supposed to do. It arrives with <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      pl: "Do wczoraj SkillFishOS miał siedem okien: Tuner, Wentylator, Monitor, Jądro, Migawki, AI i resztę. Teraz jest <strong>jedno</strong>, z dwunastoma sekcjami w kolumnie po lewej, a w nim także rzeczy, które dotąd wymagały terminala: nasza Mesa włączana dla Steam, dla Heroic albo dla całego systemu, planista startujący razem z grą, instalator GE-Proton 11, profile. Tuner napisano na nowo wokół prawdziwej krzywej governora: piętnaście przeciąganych punktów, sufit i Zastosuj, które <strong>uruchamia krzywą na próbę</strong> z odliczaniem, podczas gdy stara zostaje na dysku. Jeśli płyta się zawiesi, wraca z dobrą krzywą. Te same sekcje są w Remote Managerze. Po zmianie powtórzyliśmy testy: Cyberpunk 98 fps, Wukong 50, GravityMark 26 950, Superposition 12 560, czyli <strong>te same liczby co wcześniej</strong>, bo tak ma działać okno. Przychodzi z <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      uk: "До вчора SkillFishOS мав сім вікон: Тюнер, Вентилятор, Монітор, Ядро, Знімки, ШІ та решту. Тепер є <strong>одне</strong>, з дванадцятьма розділами в колонці ліворуч, і в ньому є й те, що раніше потребувало термінала: наша Mesa, яку вмикаєш для Steam, для Heroic або для всієї системи, планувальник, що стартує разом із грою, встановлювач GE-Proton 11, профілі. Тюнер переписано навколо справжньої кривої governor: п'ятнадцять вузлів, які тягнеш, стеля і «Застосувати», яке <strong>запускає криву на пробу</strong> зі зворотним відліком, поки стара лишається на диску. Якщо плата зависне, вона повернеться з доброю кривою. Ті самі розділи є в Remote Manager. Після зміни ми повторили тести: Cyberpunk 98 fps, Wukong 50, GravityMark 26 950, Superposition 12 560, тобто <strong>ті самі числа, що й раніше</strong>, бо саме так має поводитися вікно. Приходить із <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      ru: "До вчерашнего дня у SkillFishOS было семь окон: Тюнер, Вентилятор, Монитор, Ядро, Снимки, ИИ и остальные. Теперь оно <strong>одно</strong>, с двенадцатью разделами в колонке слева, и в нём есть и то, что раньше требовало терминала: наша Mesa, включаемая для Steam, для Heroic или для всей системы, планировщик, стартующий вместе с игрой, установщик GE-Proton 11, профили. Тюнер переписан вокруг настоящей кривой governor: пятнадцать перетаскиваемых узлов, потолок и «Применить», которое <strong>запускает кривую на пробу</strong> с обратным отсчётом, пока старая остаётся на диске. Если плата зависнет, она вернётся с хорошей кривой. Те же разделы есть в Remote Manager. После изменения мы повторили тесты: Cyberpunk 98 fps, Wukong 50, GravityMark 26 950, Superposition 12 560, то есть <strong>те же числа, что и раньше</strong>, как и положено окну. Приходит с <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      es: "Hasta ayer SkillFishOS tenía siete ventanas: Tuner, Ventilador, Monitor, Kernel, Instantáneas, IA y el resto. Ahora hay <strong>una sola</strong>, con doce secciones en la columna de la izquierda, y dentro hay también cosas que antes se hacían desde el terminal: nuestra Mesa activable para Steam, para Heroic o para todo el sistema, el planificador que arranca con los juegos, la instalación de GE-Proton 11, los perfiles. El Tuner se ha reescrito en torno a la curva real del governor: quince puntos que se arrastran, el techo, y un Aplicar que <strong>pone la curva a prueba</strong> con una cuenta atrás mientras la vieja se queda en el disco. Si la placa se cuelga, vuelve con la curva buena. Las mismas secciones están en el Remote Manager. Hemos repetido los benchmarks tras el cambio: Cyberpunk 98 fps, Wukong 50, GravityMark 26.950, Superposition 12.560, es decir <strong>los mismos números de antes</strong>, que es lo que debe hacer una ventana. Llega con <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      pt: "Até ontem o SkillFishOS tinha sete janelas: Tuner, Ventoinha, Monitor, Kernel, Snapshots, IA e o resto. Agora há <strong>uma só</strong>, com doze secções na coluna à esquerda, e lá dentro estão também coisas que antes se faziam pelo terminal: a nossa Mesa para ligar no Steam, no Heroic ou em todo o sistema, o escalonador que arranca com os jogos, a instalação do GE-Proton 11, os perfis. O Tuner foi reescrito à volta da curva real do governor: quinze pontos que se arrastam, o teto, e um Aplicar que <strong>põe a curva à prova</strong> com uma contagem decrescente enquanto a antiga fica no disco. Se a placa bloquear, volta com a curva boa. As mesmas secções estão no Remote Manager. Repetimos os benchmarks depois da mudança: Cyberpunk 98 fps, Wukong 50, GravityMark 26.950, Superposition 12.560, ou seja <strong>os mesmos números de antes</strong>, que é o que uma janela deve fazer. Chega com <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      de: "Bis gestern hatte SkillFishOS sieben Fenster: Tuner, Lüfter, Monitor, Kernel, Snapshots, KI und den Rest. Jetzt gibt es <strong>eines</strong>, mit zwölf Bereichen in der Spalte links, und darin steckt auch, was bisher ein Terminal brauchte: unsere Mesa, einschaltbar für Steam, für Heroic oder das ganze System, der Scheduler, der mit dem Spiel startet, der GE-Proton-11-Installer, die Profile. Der Tuner wurde um die echte Kurve des Governors neu geschrieben: fünfzehn Knoten zum Ziehen, die Obergrenze, und ein Anwenden, das die Kurve <strong>auf Probe laufen lässt</strong>, mit Countdown, während die alte auf der Platte bleibt. Hängt die Karte, kommt sie mit der guten Kurve zurück. Dieselben Bereiche gibt es im Remote Manager. Wir haben die Benchmarks nach der Änderung wiederholt: Cyberpunk 98 fps, Wukong 50, GravityMark 26.950, Superposition 12.560, also <strong>dieselben Zahlen wie vorher</strong>, was ein Fenster tun soll. Es kommt mit <code>sudo apt update &amp;&amp; sudo apt upgrade</code>.",
      fr: "Jusqu'à hier SkillFishOS avait sept fenêtres : Tuner, Ventilateur, Moniteur, Noyau, Instantanés, IA et le reste. Maintenant il n'y en a <strong>qu'une</strong>, avec douze sections dans la colonne de gauche, et elle contient aussi ce qui demandait un terminal : notre Mesa à activer pour Steam, pour Heroic ou pour tout le système, l'ordonnanceur qui démarre avec le jeu, l'installation de GE-Proton 11, les profils. Le Tuner a été réécrit autour de la vraie courbe du governor : quinze points que l'on glisse, le plafond, et un Appliquer qui <strong>met la courbe à l'essai</strong> avec un compte à rebours pendant que l'ancienne reste sur le disque. Si la carte se bloque, elle revient avec la bonne courbe. Les mêmes sections sont dans le Remote Manager. Nous avons refait les benchmarks après le changement : Cyberpunk 98 fps, Wukong 50, GravityMark 26 950, Superposition 12 560, c'est-à-dire <strong>les mêmes chiffres qu'avant</strong>, ce qui est exactement ce qu'une fenêtre doit faire. Cela arrive avec <code>sudo apt update &amp;&amp; sudo apt upgrade</code>."
    },
  },
'''
a = "export const news: Post[] = [\n"
assert a in t
t = t.replace(a, a + voce, 1)
open(p, "w", encoding="utf-8").write(t)
print("novita' aggiunta")
