#!/usr/bin/env python3
"""The news entry for the AI section and the documentation that follows the
merged window.

    aggiungi-novita-1209.py <repo>
"""
import os
import sys

repo = sys.argv[1] if len(sys.argv) > 1 else "."
p = os.path.join(repo, "website", "src", "news.ts")

VOCE = """  {
    // ai-control-center-2026-09
    data: '2026-09-12',
    quando: { it: "12 settembre 2026", en: "12 September 2026", pl: "12 września 2026", uk: "12 вересня 2026", ru: "12 сентября 2026", es: "12 de septiembre de 2026", pt: "12 de setembro de 2026", de: "12. September 2026", fr: "12 septembre 2026" },
    etichetta: { it: "aggiornamento", en: "update", pl: "aktualizacja", uk: "оновлення", ru: "обновление", es: "actualización", pt: "atualização", de: "Aktualisierung", fr: "mise à jour" },
    titolo: {
      it: "La sezione AI pilota davvero il motore, e la documentazione parla di una finestra sola",
      en: "The AI section really drives the engine, and the documentation talks about one window",
      pl: "Sekcja AI naprawdę steruje silnikiem, a dokumentacja mówi o jednym oknie",
      uk: "Розділ ШІ справді керує рушієм, а документація говорить про одне вікно",
      ru: "Раздел ИИ действительно управляет движком, а документация говорит об одном окне",
      es: "La sección IA pilota de verdad el motor, y la documentación habla de una sola ventana",
      pt: "A secção IA pilota mesmo o motor, e a documentação fala de uma só janela",
      de: "Der KI-Bereich steuert den Motor wirklich, und die Dokumentation spricht von einem Fenster",
      fr: "La section IA pilote vraiment le moteur, et la documentation parle d'une seule fenêtre",
    },
    testo: {
      it: "Nel Control Center la sezione AI era un interruttore e un collegamento. Unsloth Studio ha una sua API, quindi adesso la finestra la usa: versione con il controllo degli aggiornamenti e <b>Aggiorna</b> in un clic, il primo accesso fatto da qui (Unsloth genera una password a caso quando si installa e si spegne da solo dopo un'ora se non viene cambiata), la chiave API creata insieme e condivisa con il Remote Manager, i modelli sul disco con quantizzazione e dimensione, il download dei GGUF dall'Hub di Hugging Face scrivendo il nome del repository, una chat di prova sull'API con i token al secondo misurati, e il motore apribile sulla rete locale. Stessa cosa nel Remote Manager, dal browser.<br><br>Con l'occasione abbiamo riscritto la documentazione: le vecchie applicazioni separate non esistono più da settembre, e le pagine che le descrivevano sono state sostituite da quella del <a href=\\"/docs/control-center\\">Control Center</a>, con schermate nuove. Nel Tuner la VRAM guadagna i preset da 512 MB e 1 GB, e i 2048 MB tornano tra i valori buoni: la nota che li dava per rotti era sbagliata.",
      en: "In the Control Center the AI section was a switch and a link. Unsloth Studio has an API of its own, so the window now uses it: the version with the update check and <b>Update</b> in one click, the first sign-in done here (Unsloth generates a random password when it installs and shuts itself down after an hour if that password is not changed), the API key created with it and shared with the Remote Manager, the models on disk with quantization and size, GGUF downloads from the Hugging Face Hub by typing the repository name, a chat test over the API with the measured tokens per second, and the engine opened to the local network. The same in the Remote Manager, from a browser.<br><br>While we were at it we rewrote the documentation: the old separate applications have been gone since September, and the pages describing them were replaced by the <a href=\\"/en/docs/control-center\\">Control Center</a> one, with new screenshots. In the Tuner the VRAM gains 512 MB and 1 GB presets, and 2048 MB is back among the good values: the note calling it broken was wrong.",
      pl: "W Control Center sekcja AI była przełącznikiem i odnośnikiem. Unsloth Studio ma własne API, więc okno teraz z niego korzysta: wersja ze sprawdzaniem aktualizacji i <b>Aktualizuj</b> jednym kliknięciem, pierwsze logowanie zrobione stąd (Unsloth przy instalacji tworzy losowe hasło i wyłącza się sam po godzinie, jeśli hasło nie zostanie zmienione), klucz API powstający razem z nim i dzielony z Remote Managerem, modele na dysku z kwantyzacją i rozmiarem, pobieranie GGUF z Hubu Hugging Face po nazwie repozytorium, próbny czat na API ze zmierzonymi tokenami na sekundę i silnik otwierany na sieć lokalną. To samo w Remote Managerze, z przeglądarki.<br><br>Przy okazji przepisaliśmy dokumentację: dawnych osobnych aplikacji nie ma od września, a opisujące je strony zastąpiła strona <a href=\\"/pl/docs/control-center\\">Control Center</a>, z nowymi zrzutami. W Tunerze VRAM dostaje presety 512 MB i 1 GB, a 2048 MB wraca do dobrych wartości: notka o tym, że nie działa, była błędna.",
      uk: "У Control Center розділ ШІ був вимикачем і посиланням. Unsloth Studio має власний API, тож вікно тепер ним користується: версія з перевіркою оновлень і <b>Оновити</b> в один клік, перший вхід зроблений звідси (Unsloth створює випадковий пароль під час встановлення і вимикається сам через годину, якщо пароль не змінити), ключ API, створений разом із ним і переданий Remote Manager, моделі на диску з квантуванням і розміром, завантаження GGUF з Hub Hugging Face за назвою репозиторію, проба чату на API з виміряними токенами за секунду і рушій, відкритий у локальну мережу. Те саме в Remote Manager, із браузера.<br><br>Заразом ми переписали документацію: колишніх окремих програм немає з вересня, а сторінки, що їх описували, замінила сторінка <a href=\\"/uk/docs/control-center\\">Control Center</a>, з новими знімками. У Тюнері VRAM отримує пресети 512 МБ і 1 ГБ, а 2048 МБ повертається до хороших значень: примітка про поломку була хибною.",
      ru: "В Control Center раздел ИИ был переключателем и ссылкой. У Unsloth Studio есть свой API, и теперь окно им пользуется: версия с проверкой обновлений и <b>Обновить</b> в один клик, первый вход, сделанный отсюда (Unsloth создаёт случайный пароль при установке и выключается сам через час, если пароль не сменить), ключ API, созданный вместе с ним и переданный Remote Manager, модели на диске с квантованием и размером, загрузка GGUF из Hub Hugging Face по имени репозитория, проба чата на API с измеренными токенами в секунду и движок, открываемый в локальную сеть. То же самое в Remote Manager, из браузера.<br><br>Заодно мы переписали документацию: прежних отдельных приложений нет с сентября, а описывавшие их страницы заменила страница <a href=\\"/ru/docs/control-center\\">Control Center</a>, с новыми снимками. В Тюнере VRAM получает пресеты 512 МБ и 1 ГБ, а 2048 МБ возвращается в число хороших значений: заметка о поломке была неверной.",
      es: "En el Control Center la sección IA era un interruptor y un enlace. Unsloth Studio tiene su propia API, así que ahora la ventana la usa: la versión con la comprobación de actualizaciones y <b>Actualizar</b> en un clic, el primer acceso hecho desde aquí (Unsloth genera una contraseña al azar al instalarse y se apaga solo al cabo de una hora si no se cambia), la clave API creada a la vez y compartida con el Remote Manager, los modelos en disco con cuantización y tamaño, la descarga de GGUF del Hub de Hugging Face escribiendo el nombre del repositorio, una prueba de chat sobre la API con los tokens por segundo medidos, y el motor abierto a la red local. Lo mismo en el Remote Manager, desde el navegador.<br><br>De paso hemos reescrito la documentación: las antiguas aplicaciones separadas ya no existen desde septiembre, y las páginas que las describían las ha sustituido la del <a href=\\"/es/docs/control-center\\">Control Center</a>, con capturas nuevas. En el Tuner la VRAM gana los preajustes de 512 MB y 1 GB, y los 2048 MB vuelven a los valores buenos: la nota que los daba por rotos era falsa.",
      pt: "No Control Center a secção IA era um interruptor e uma ligação. O Unsloth Studio tem uma API própria, por isso a janela passa a usá-la: a versão com a verificação de atualizações e <b>Atualizar</b> num clique, o primeiro acesso feito aqui (o Unsloth gera uma senha ao acaso quando se instala e desliga-se sozinho ao fim de uma hora se ela não for mudada), a chave API criada com ela e partilhada com o Remote Manager, os modelos em disco com quantização e tamanho, a transferência de GGUF do Hub da Hugging Face escrevendo o nome do repositório, um teste de chat sobre a API com os tokens por segundo medidos, e o motor aberto à rede local. O mesmo no Remote Manager, pelo navegador.<br><br>Já agora reescrevemos a documentação: as antigas aplicações separadas deixaram de existir em setembro, e as páginas que as descreviam foram substituídas pela do <a href=\\"/pt/docs/control-center\\">Control Center</a>, com imagens novas. No Tuner a VRAM ganha as predefinições de 512 MB e 1 GB, e os 2048 MB voltam aos valores bons: a nota que os dava como avariados estava errada.",
      de: "Im Control Center war der KI-Bereich ein Schalter und ein Link. Unsloth Studio hat eine eigene API, also nutzt das Fenster sie jetzt: die Version mit Aktualisierungsprüfung und <b>Aktualisieren</b> in einem Klick, die erste Anmeldung von hier aus (Unsloth erzeugt bei der Installation ein zufälliges Passwort und schaltet sich nach einer Stunde selbst ab, wenn es nicht geändert wird), der API-Schlüssel, der dabei entsteht und mit dem Remote Manager geteilt wird, die Modelle auf der Platte mit Quantisierung und Größe, GGUF-Downloads aus dem Hugging-Face-Hub über den Namen des Repositorys, ein Chat-Test über die API mit den gemessenen Token pro Sekunde und der Motor, der sich ins lokale Netz öffnen lässt. Dasselbe im Remote Manager, im Browser.<br><br>Bei der Gelegenheit haben wir die Dokumentation neu geschrieben: die alten getrennten Anwendungen gibt es seit September nicht mehr, und die Seiten, die sie beschrieben, wurden durch die Seite <a href=\\"/de/docs/control-center\\">Control Center</a> ersetzt, mit neuen Bildschirmfotos. Im Tuner bekommt der VRAM die Vorgaben 512 MB und 1 GB, und 2048 MB stehen wieder bei den guten Werten: die Notiz, die sie für kaputt erklärte, war falsch.",
      fr: "Dans le Control Center, la section IA était un interrupteur et un lien. Unsloth Studio a sa propre API, la fenêtre s'en sert donc désormais : la version avec la vérification des mises à jour et <b>Mettre à jour</b> en un clic, la première connexion faite ici (Unsloth génère un mot de passe au hasard à l'installation et s'éteint tout seul au bout d'une heure s'il n'est pas changé), la clé API créée en même temps et partagée avec le Remote Manager, les modèles sur le disque avec quantification et taille, le téléchargement des GGUF depuis le Hub Hugging Face en tapant le nom du dépôt, un essai de chat sur l'API avec les tokens par seconde mesurés, et le moteur ouvrable sur le réseau local. Pareil dans le Remote Manager, depuis le navigateur.<br><br>Au passage nous avons réécrit la documentation : les anciennes applications séparées n'existent plus depuis septembre, et les pages qui les décrivaient ont été remplacées par celle du <a href=\\"/fr/docs/control-center\\">Control Center</a>, avec de nouvelles captures. Dans le Tuner, la VRAM gagne les préréglages 512 Mo et 1 Go, et les 2048 Mo reviennent parmi les bonnes valeurs : la note qui les disait cassés était fausse.",
    },
  },
"""

with open(p, encoding="utf-8") as f:
    s = f.read()
if "ai-control-center-2026-09" in s:
    raise SystemExit("la voce c'e' gia'")
s = s.replace("export const news: Post[] = [\n", "export const news: Post[] = [\n" + VOCE, 1)
with open(p, "w", encoding="utf-8", newline="\n") as f:
    f.write(s)
print("voce aggiunta")
