# shellprocess@post_removeuser.conf on Skillfishos, penguins-eggs 26.5.12
---
message: Finishing up the new system...
dontChroot: false
timeout: 300
script:
  - /usr/local/bin/skillfish-clean-live-autologin || true
  - /usr/local/bin/skillfish-games-subvolume prepara || true
